#!/bin/bash
mkdir Task1
cd Task1
for x in {1..100};do
	touch file$x
	cat /dev/urandom | tr -cd [:alnum:]| head -c 16 > file$x
	done
fallocate -l 10K file*
touch -d "2 days ago" file*
chmod 444 file*
sudo chattr +i file*
cd ..