#!/bin/bash
mkdir Task1
cd Task1
for x in {1..100};do
	touch ./file$x
	cat /dev/urandom | tr -cd [:alnum:]| head -c 16 > file$x
	fallocate -l 10K file$x
	touch -d "2 days ago" file$x
	chmod 444 file$x
	sudo chattr +i file$x
done
cd ..